package com.dayofpi.super_block_world.item.registry;

import com.dayofpi.super_block_world.Main;
import com.dayofpi.super_block_world.block.registry.BlockList;
import com.dayofpi.super_block_world.entity.registry.EntityList;
import com.dayofpi.super_block_world.entity.types.ModBoatEntity;
import com.dayofpi.super_block_world.item.types.*;
import com.dayofpi.super_block_world.world.FluidList;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.entity.EquipmentSlot;
import net.minecraft.item.*;
import net.minecraft.util.Identifier;
import net.minecraft.util.Rarity;
import net.minecraft.util.registry.Registry;


public class ItemList {
    public static final ArmorMaterial BUZZY_ARMOR_MATERIAL = new BuzzyArmorMaterial();
    public static final ArmorMaterial JUMP_ARMOR_MATERIAL = new JumpArmorMaterial();

    public static final Item POWER_STAR = new PowerStarItem(new FabricItemSettings().rarity(Rarity.RARE).group(CreativeTabs.ITEM_GROUP));
    public static final Item YOSHI_FRUIT = new Item(new FabricItemSettings().food(FoodComponents.YOSHI_FRUIT).group(CreativeTabs.ITEM_GROUP));
    public static final Item YOSHI_COOKIE = new Item(new FabricItemSettings().food(FoodComponents.YOSHI_COOKIE).group(CreativeTabs.ITEM_GROUP));
    public static final Item TURNIP = new TurnipItem(new FabricItemSettings().maxCount(16).group(CreativeTabs.ITEM_GROUP));
    public static final Item HAMMER = new HammerItem(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP).maxDamage(50));
    public static final Item BOMB = new BombItem(new FabricItemSettings().maxCount(16).group(CreativeTabs.ITEM_GROUP));
    public static final Item SUPER_MUSHROOM = new Item(new FabricItemSettings().food(FoodComponents.SUPER_MUSHROOM).maxCount(16).group(CreativeTabs.ITEM_GROUP));
    public static final Item GOLDEN_MUSHROOM = new Item(new FabricItemSettings().food(FoodComponents.GOLDEN_MUSHROOM).maxCount(16).group(CreativeTabs.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item ONE_UP = new OneUpItem(new FabricItemSettings().food(FoodComponents.ONE_UP).maxCount(16).group(CreativeTabs.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item POISON_MUSHROOM = new Item(new FabricItemSettings().food(FoodComponents.POISON_MUSHROOM).maxCount(16).group(CreativeTabs.ITEM_GROUP).rarity(Rarity.UNCOMMON));
    public static final Item FIRE_FLOWER = new FireFlowerItem(new FabricItemSettings().maxDamage(16).group(CreativeTabs.ITEM_GROUP));
    public static final Item COIN = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item RAW_BRONZE = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BRONZE_INGOT = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static ToolItem BRONZE_PICKAXE = new PickaxeItem(BronzeToolMaterial.INSTANCE, 2, 0.0F, new Item.Settings().group(ItemGroup.TOOLS)){};
    public static final Item TROOP_HIDE = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item CLOUD_PUFF = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item SPIKE = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BUZZY_SHELL_PIECE = new Item(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BUZZY_SHELL = new ArmorItem(BUZZY_ARMOR_MATERIAL, EquipmentSlot.HEAD, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item JUMP_BOOTS = new ArmorItem(JUMP_ARMOR_MATERIAL, EquipmentSlot.FEET, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BOTTLE_O_GHOST = new Item(new FabricItemSettings().recipeRemainder(Items.GLASS_BOTTLE).group(CreativeTabs.ITEM_GROUP));
    public static final Item GREEN_MUSHROOM_ON_A_STICK = new OnAStickItem<>(new FabricItemSettings().group(CreativeTabs.ITEM_GROUP).maxDamage(25), EntityList.BUZZY_BEETLE, 2);
    public static final Item AMANITA_BOAT = new ModBoatItem(ModBoatEntity.Type.AMANITA, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP).maxCount(1));
    public static final Item POISON_BUCKET = new BucketItem(FluidList.STILL_POISON, new FabricItemSettings().recipeRemainder(Items.BUCKET).maxCount(1).group(CreativeTabs.ITEM_GROUP));
    public static final Item MOO_MOO_SPAWN_EGG = new SpawnEggItem(EntityList.MOO_MOO, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item GOOMBA_SPAWN_EGG = new SpawnEggItem(EntityList.GOOMBA, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BOB_OMB_SPAWN_EGG = new SpawnEggItem(EntityList.BOB_OMB, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BOO_SPAWN_EGG = new SpawnEggItem(EntityList.BOO, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item BUZZY_BEETLE_SPAWN_EGG = new SpawnEggItem(EntityList.BUZZY_BEETLE, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item SPIKE_TOP_SPAWN_EGG = new SpawnEggItem(EntityList.SPIKE_TOP, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item NIPPER_PLANT_SPAWN_EGG = new SpawnEggItem(EntityList.NIPPER_PLANT, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item STINGBY_SPAWN_EGG = new SpawnEggItem(EntityList.STINGBY, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));
    public static final Item ROTTEN_MUSHROOM_SPAWN_EGG = new SpawnEggItem(EntityList.ROTTEN_MUSHROOM, 16777215, 16777215, new FabricItemSettings().group(CreativeTabs.ITEM_GROUP));

    public static void registerItems() {
        registerBlockItems();
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "power_star"), POWER_STAR);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yoshi_fruit"), YOSHI_FRUIT);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yoshi_cookie"), YOSHI_COOKIE);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "turnip"), TURNIP);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "hammer"), HAMMER);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bomb"), BOMB);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "buzzy_shell"), BUZZY_SHELL);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "jump_boots"), JUMP_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "super_mushroom"), SUPER_MUSHROOM);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "golden_mushroom"), GOLDEN_MUSHROOM);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "one_up"), ONE_UP);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "poison_mushroom"), POISON_MUSHROOM);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "fire_flower"), FIRE_FLOWER);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "coin"), COIN);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "raw_bronze"), RAW_BRONZE);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bronze_ingot"), BRONZE_INGOT);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "troop_hide"), TROOP_HIDE);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "cloud_puff"), CLOUD_PUFF);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spike"), SPIKE);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "buzzy_shell_piece"), BUZZY_SHELL_PIECE);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "green_mushroom_on_a_stick"), GREEN_MUSHROOM_ON_A_STICK);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_boat"), AMANITA_BOAT);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bottle_o_ghost"), BOTTLE_O_GHOST);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "poison_bucket"), POISON_BUCKET);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/moo_moo"), MOO_MOO_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/goomba"), GOOMBA_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/bob_omb"), BOB_OMB_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/boo"), BOO_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/buzzy_beetle"), BUZZY_BEETLE_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/spike_top"), SPIKE_TOP_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/nipper_plant"), NIPPER_PLANT_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/stingby"), STINGBY_SPAWN_EGG);
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spawn_eggs/rotten_mushroom"), ROTTEN_MUSHROOM_SPAWN_EGG);
    }

    public static void registerBlockItems() {
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "warp_frame"), new BlockItem(BlockList.WARP_FRAME, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "warp_pipe"), new BlockItem(BlockList.WARP_PIPE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "warp_pipe_body"), new BlockItem(BlockList.WARP_PIPE_BODY, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "empty_block"), new BlockItem(BlockList.EMPTY_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "question_block"), new BlockItem(BlockList.QUESTION_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP).rarity(Rarity.UNCOMMON)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "coin_block"), new BlockItem(BlockList.COIN_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP).rarity(Rarity.UNCOMMON)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "spike_trap"), new BlockItem(BlockList.SPIKE_TRAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "jump_block"), new BlockItem(BlockList.JUMP_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "redstone_trampoline"), new BlockItem(BlockList.REDSTONE_TRAMPOLINE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "trampoline"), new BlockItem(BlockList.TRAMPOLINE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "stone_torch"), new BlockItem(BlockList.STONE_TORCH, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "boo_lantern"), new BlockItem(BlockList.BOO_LANTERN, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "donut_block"), new BlockItem(BlockList.DONUT_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstool_grass"), new BlockItem(BlockList.TOADSTOOL_GRASS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstool_turf"), new BlockItem(BlockList.TOADSTOOL_TURF, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstool_soil"), new BlockItem(BlockList.TOADSTOOL_SOIL, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "coarse_toadstool_soil"), new BlockItem(BlockList.COARSE_TOADSTOOL_SOIL, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstool_farmland"), new BlockItem(BlockList.TOADSTOOL_FARMLAND, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstool_path"), new BlockItem(BlockList.TOADSTOOL_PATH, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gritzy_sand"), new BlockItem(BlockList.GRITZY_SAND, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "seastone"), new BlockItem(BlockList.SEASTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "seastone_bricks"), new BlockItem(BlockList.SEASTONE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "happy_cloud"), new BlockItem(BlockList.HAPPY_CLOUD, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "cloud_block"), new BlockItem(BlockList.CLOUD_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "cloud_slab"), new BlockItem(BlockList.CLOUD_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate"), new BlockItem(BlockList.VANILLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_bricks"), new BlockItem(BlockList.VANILLATE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_tiles"), new BlockItem(BlockList.VANILLATE_TILES, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_crumble"), new BlockItem(BlockList.VANILLATE_CRUMBLE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_slab"), new BlockItem(BlockList.VANILLATE_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_stairs"), new BlockItem(BlockList.VANILLATE_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_brick_slab"), new BlockItem(BlockList.VANILLATE_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vanillate_brick_stairs"), new BlockItem(BlockList.VANILLATE_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "topped_vanillate"), new BlockItem(BlockList.TOPPED_VANILLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "coal_topped_vanillate"), new BlockItem(BlockList.COAL_TOPPED_VANILLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "iron_topped_vanillate"), new BlockItem(BlockList.IRON_TOPPED_VANILLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gold_topped_vanillate"), new BlockItem(BlockList.GOLD_TOPPED_VANILLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amethyst_ore"), new BlockItem(BlockList.AMETHYST_ORE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bronze_ore"), new BlockItem(BlockList.BRONZE_ORE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "raw_bronze_block"), new BlockItem(BlockList.RAW_BRONZE_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bronze_block"), new BlockItem(BlockList.BRONZE_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bronze_slab"), new BlockItem(BlockList.BRONZE_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bronze_stairs"), new BlockItem(BlockList.BRONZE_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone"), new BlockItem(BlockList.TOADSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "smooth_toadstone"), new BlockItem(BlockList.SMOOTH_TOADSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "chiseled_toadstone"), new BlockItem(BlockList.CHISELED_TOADSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone_bricks"), new BlockItem(BlockList.TOADSTONE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone_slab"), new BlockItem(BlockList.TOADSTONE_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone_stairs"), new BlockItem(BlockList.TOADSTONE_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone_brick_slab"), new BlockItem(BlockList.TOADSTONE_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "toadstone_brick_stairs"), new BlockItem(BlockList.TOADSTONE_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone"), new BlockItem(BlockList.GLOOMSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "smooth_gloomstone"), new BlockItem(BlockList.SMOOTH_GLOOMSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "chiseled_gloomstone"), new BlockItem(BlockList.CHISELED_GLOOMSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone_bricks"), new BlockItem(BlockList.GLOOMSTONE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone_slab"), new BlockItem(BlockList.GLOOMSTONE_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone_stairs"), new BlockItem(BlockList.GLOOMSTONE_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone_brick_slab"), new BlockItem(BlockList.GLOOMSTONE_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "gloomstone_brick_stairs"), new BlockItem(BlockList.GLOOMSTONE_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "hardstone"), new BlockItem(BlockList.HARDSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "polished_hardstone"), new BlockItem(BlockList.POLISHED_HARDSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "chiseled_hardstone"), new BlockItem(BlockList.CHISELED_HARDSTONE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "hardstone_pillar"), new BlockItem(BlockList.HARDSTONE_PILLAR, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "hardstone_bricks"), new BlockItem(BlockList.HARDSTONE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "cracked_hardstone_bricks"), new BlockItem(BlockList.CRACKED_HARDSTONE_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "polished_hardstone_slab"), new BlockItem(BlockList.POLISHED_HARDSTONE_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "polished_hardstone_stairs"), new BlockItem(BlockList.POLISHED_HARDSTONE_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "hardstone_brick_slab"), new BlockItem(BlockList.HARDSTONE_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "hardstone_brick_stairs"), new BlockItem(BlockList.HARDSTONE_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "golden_bricks"), new BlockItem(BlockList.GOLDEN_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "golden_brick_slab"), new BlockItem(BlockList.GOLDEN_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "golden_brick_stairs"), new BlockItem(BlockList.GOLDEN_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "crystal_bricks"), new BlockItem(BlockList.CRYSTAL_BRICKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "crystal_brick_slab"), new BlockItem(BlockList.CRYSTAL_BRICK_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "crystal_brick_stairs"), new BlockItem(BlockList.CRYSTAL_BRICK_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_log"), new BlockItem(BlockList.AMANITA_LOG, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_wood"), new BlockItem(BlockList.AMANITA_WOOD, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "stripped_amanita_log"), new BlockItem(BlockList.STRIPPED_AMANITA_LOG, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "stripped_amanita_wood"), new BlockItem(BlockList.STRIPPED_AMANITA_WOOD, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_planks"), new BlockItem(BlockList.AMANITA_PLANKS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_slab"), new BlockItem(BlockList.AMANITA_SLAB, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_stairs"), new BlockItem(BlockList.AMANITA_STAIRS, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_fence"), new BlockItem(BlockList.AMANITA_FENCE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_fence_gate"), new BlockItem(BlockList.AMANITA_FENCE_GATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_door"), new BlockItem(BlockList.AMANITA_DOOR, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_trapdoor"), new BlockItem(BlockList.AMANITA_TRAPDOOR, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_button"), new BlockItem(BlockList.AMANITA_BUTTON, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_pressure_plate"), new BlockItem(BlockList.AMANITA_PRESSURE_PLATE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_sign"), new SignItem(new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP).maxCount(16), BlockList.AMANITA_SIGN, BlockList.AMANITA_WALL_SIGN));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_leaves"), new BlockItem(BlockList.AMANITA_LEAVES, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "fruiting_amanita_leaves"), new BlockItem(BlockList.FRUITING_AMANITA_LEAVES, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_sapling"), new BlockItem(BlockList.AMANITA_SAPLING, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "amanita_carpet"), new BlockItem(BlockList.AMANITA_CARPET, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yellow_flowerbed"), new BlockItem(BlockList.YELLOW_FLOWERBED, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "blue_songflower"), new BlockItem(BlockList.BLUE_SONGFLOWER, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "pink_songflower"), new BlockItem(BlockList.PINK_SONGFLOWER, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yellow_songflower"), new BlockItem(BlockList.YELLOW_SONGFLOWER, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "pawflower"), new BlockItem(BlockList.PAWFLOWER, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "fire_tulip"), new BlockItem(BlockList.FIRE_TULIP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "horsetail"), new BlockItem(BlockList.HORSETAIL, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "bush"), new BlockItem(BlockList.BUSH, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "vegetable"), new BlockItem(BlockList.VEGETABLE, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "beanstalk"), new BlockItem(BlockList.BEANSTALK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "budding_beanstalk"), new BlockItem(BlockList.BUDDING_BEANSTALK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "piranha_lily"), new PiranhaLilyItem(BlockList.PIRANHA_LILY, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "muncher"), new BlockItem(BlockList.MUNCHER, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "strawberry_coral"), new BlockItem(BlockList.STRAWBERRY_CORAL, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "strawberry_coral_block"), new BlockItem(BlockList.STRAWBERRY_CORAL_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "beanstalk_block"), new BlockItem(BlockList.BEANSTALK_BLOCK, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "mushroom_stem"), new BlockItem(BlockList.MUSHROOM_STEM, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "brown_mushroom_cap"), new BlockItem(BlockList.BROWN_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "red_mushroom_cap"), new BlockItem(BlockList.RED_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "green_mushroom_cap"), new BlockItem(BlockList.GREEN_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "pink_mushroom_cap"), new BlockItem(BlockList.PINK_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yellow_mushroom_cap"), new BlockItem(BlockList.YELLOW_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "orange_mushroom_cap"), new BlockItem(BlockList.ORANGE_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "purple_mushroom_cap"), new BlockItem(BlockList.PURPLE_MUSHROOM_CAP, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "green_mushroom"), new BlockItem(BlockList.GREEN_MUSHROOM, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "pink_mushroom"), new BlockItem(BlockList.PINK_MUSHROOM, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "yellow_mushroom"), new BlockItem(BlockList.YELLOW_MUSHROOM, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "orange_mushroom"), new BlockItem(BlockList.ORANGE_MUSHROOM, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(Main.MOD_ID, "purple_mushroom"), new BlockItem(BlockList.PURPLE_MUSHROOM, new FabricItemSettings().group(CreativeTabs.BLOCK_GROUP)));
    }
}
